name: Run-Jest-Tests

on:
  workflow_dispatch:
    inputs:
      stackname:
        description: "Host name, i.e. 'api.highfidelity.com', `api-staging-latest.highfidelity.com`, or 'loadbalancer-my-stack-01.highfidelity.io'"
        required: true
        default: api-staging-latest.highfidelity.com
    branches:
      - main
      - gha
  push:
    branches:
      - main
      - gha
 

jobs:
  Run-Jest-Tests:
    runs-on: ubuntu-latest
    if: github.event.pusher.namen != 'hifibuild'

    steps:
      - name: View Commit Author
        run: echo "The last push was made by a user named ${{ github.event.pusher.name }}."
      
      - uses: actions/checkout@v2
    
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Modules
        run: npm i

      # Run unit tests
      - name: Run Jest Unit Tests
        run: |
          ./node_modules/.bin/jest test -- unit --ci -b
          echo "Exited with '$?'"

      - name: Unit Tests Passed
        if: ${{ success() }}
        run: |
          curl --request POST --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'content-type: application/json' --data '{ "context": "tests", "state": "success", "description": "Tests passed", "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'
      - name: Unit Tests Failed
        if: ${{ failure() }}
        run: |
          curl --request POST --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'content-type: application/json' --data '{ "context": "tests", "state": "failure", "description": "Tests failed", "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'

     # Run integration tests
      - name: Decrypt auth file
        run: ./.github/scripts/decryptAuthFile.sh
        env:
          TESTING_AUTH_DECRYPTION_KEY: ${{ secrets.TESTING_AUTH_DECRYPTION_KEY }}
          STACKNAME: ${{ github.event.inputs.stackname || 'api-staging-latest.highfidelity.com' }}
        

      - name: Run Jest Integration Tests
        run: npm run test -- integration --ci

      # TODO
      - name: Integration Tests Passed
        if: ${{ success() }}
        run: |
          curl --request POST --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'content-type: application/json' --data '{ "context": "tests", "state": "success", "description": "Tests passed", "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'

      # TODO
      - name: Integration Tests Failed
        if: ${{ failure() }}
        run: |
          curl --request POST --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'content-type: application/json' --data '{ "context": "tests", "state": "failure", "description": "Tests failed", "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'
