name: Run-Jest-Unit-Tests

on:
  push:
    branches:
      - main

jobs:
  Run-Jest-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Modules
      run: npm i

    - name: Run Jest Unit Tests
      run: npm run test

    - name: Unit Tests Passed
      if: ${{ success() }}
      run: |
        curl --request POST --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'content-type: application/json' --data '{ "context": "tests", "state": "success", "description": "Tests passed", "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'

    - name: Unit Tests Failed
      if: ${{ failure() }}
      run: |
        curl --request POST --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'content-type: application/json' --data '{ "context": "tests", "state": "failure", "description": "Tests  failed", "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'